---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-display
  template:
    metadata:
      labels:
        app: event-display
    spec:
      containers:
        - name: event-display
          image: quay.io/openshift-knative/knative-eventing-sources-event-display
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  selector:
    app: event-display
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
...
